Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2018-04, with the labels that each got.

#1660 #1650 Unknown Office control ID: PictureCropToolsMenu
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1648 #1606 Fix pasting of web pictures
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteAtCursorPosition/PasteAtCursorPositionActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteAtOriginalPosition/PasteAtOriginalPositionActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteIntoGroup/PasteIntoGroupActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteLabActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFillSlide/PasteToFillSlideActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFitSlide/PasteToFitSlideActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/ReplaceWithClipboard/ReplaceWithClipboardActionHandler.cs
  PowerPointLabs/PowerPointLabs/TextCollection/PasteLabText.cs
  PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1667 #1556 Paste Lab: support "smart paste" of photos
  PowerPointLabs/PowerPointLabs/CropLab/CropToSlide.cs
  PowerPointLabs/PowerPointLabs/PasteLab/PasteToFillSlide.cs
  PowerPointLabs/PowerPointLabs/PasteLab/PasteToFitSlide.cs
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/TextCollection/CommonText.cs
  PowerPointLabs/PowerPointLabs/Utils/GraphicsUtil.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1672 #1662 Make Agenda Reference Slide sync Design's Slide Master (Theme of the slide) with other agenda slides
  PowerPointLabs/PowerPointLabs/Utils/SlideUtil.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1677 #1676 Revert back to original crop to slide for PasteToFill function
  PowerPointLabs/PowerPointLabs/CropLab/CropToSlide.cs
  PowerPointLabs/PowerPointLabs/PasteLab/PasteToFillSlide.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.resx
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
Labels: ok-2013, ok-2016, s.ToReview

#1642 #1623 replace with clipboard: preserve shape settings (existing sync formats only)
  PowerPointLabs/PowerPointLabs/PasteLab/ReplaceWithClipboard.cs
  PowerPointLabs/PowerPointLabs/Utils/ShapeUtil.cs
  PowerPointLabs/Test/UnitTest/PlaceHolderCopyTest.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1668 #1593 Inserting Shape should allow users to remain in PowerPointLabs tab
  PowerPointLabs/PowerPointLabs/Ribbon1.cs
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1655 #1213 support for syncing shadow
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFillSlide/PasteToFillSlideActionHandler.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/SyncLabController.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ShadowEffectFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatDialog.xaml.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/TextCollection/SyncLabText.cs
  PowerPointLabs/Test/FunctionalTest/SyncLabTest.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabShadowEffectTest.cs
  doc/test/SyncLab/SyncLab.pptx
  doc/test/SyncLab/SyncLab_ShadowEffect.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1671 #1213 support for syncing softedge
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/SoftEdgeEffectFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabSoftEdgeEffectTest.cs
  doc/test/SyncLab/SyncLab_SoftEdgeEffect.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1666 #1213 support for syncing reflections
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ReflectionBlurFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ReflectionDistanceFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ReflectionSizeFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ReflectionTransparencyFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabReflectionEffectTest.cs
  doc/test/SyncLab/SyncLab_ReflectionEffect.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1678 #1213 support for 3drotation
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ThreeDRotationEffectFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabThreeDRotationEffectTest.cs
  doc/test/SyncLab/SyncLab_ThreeDRotationEffect.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1673 #1213 support for syncing bevel
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/BevelBottomFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/BevelTopFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ContourColorFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/ContourWidthFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/DepthColorFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/DepthSizeFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/LightingAngleFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/LightingEffectFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/MaterialEffectFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabThreeDEffectTest.cs
  doc/test/SyncLab/SyncLab_ThreeDEffects.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1687 #1651 Consider adding Technical Troubleshooting FAQs to the User Guide
  doc/TechnicalFAQs.md
  doc/images/TechnicalFAQ/assembly-not-installed.png
  doc/images/TechnicalFAQ/cert-not-trusted.png
  doc/images/TechnicalFAQ/clickonce-cache.png
  doc/images/TechnicalFAQ/error-manifest.png
  doc/images/TechnicalFAQ/net-not-installed.png
  doc/images/TechnicalFAQ/preexisting-app.png
  doc/images/TechnicalFAQ/preexisting-app2.png
  doc/images/TechnicalFAQ/rename-vsto-file.png
  doc/images/TechnicalFAQ/vsto-as-xml.png
  doc/images/TechnicalFAQ/vsto-installer-config.png
Labels: a-Documents, a-Website
