Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2018-02, with the labels that each got.

#1579 #1576 Positions Lab: Should not require at least 2-3 shapes to be selected
  PowerPointLabs/PowerPointLabs/PositionsLab/PositionsLabMain.cs
  PowerPointLabs/Test/UnitTest/PositionsLab/PositionsLabAlignTest.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToMerge

#1566 #1498 Add a "Add" button for ShapesLab
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/AddShape/AddShapeActionHandler.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/ShapesLabController.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.Designer.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.resx
  PowerPointLabs/PowerPointLabs/TextCollection/ShapesLabText.cs
  PowerPointLabs/PowerPointLabs/Utils/ShapeUtil.cs
  PowerPointLabs/Test/FunctionalTest/ShapesLabTest.cs
  PowerPointLabs/TestInterface/IShapesLabController.cs
  doc/test/ShapesLab/ShapesLab.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1572 #1559 Refactor "global" variables in RibbonUI
  PowerPointLabs/PowerPointLabs/ActionFramework/CaptionsLab/AddCaptions/AddCaptionsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/CaptionsLab/RemoveCaptions/RemoveCaptionsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/CaptionsLab/RemoveCaptions/RemoveCaptionsEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/HighlightLab/HighlightBackground/HighlightBackgroundEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/HighlightLab/HighlightPoints/HighlightPointsEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/HighlightLab/HighlightText/HighlightTextEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/NarrationsLab/AddNarrations/AddNarrationsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/NarrationsLab/RemoveNarrations/RemoveNarrationsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/NarrationsLab/RemoveNarrations/RemoveNarrationsEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/CaptionsLab/NotesToCaptions.cs
  PowerPointLabs/PowerPointLabs/HighlightLab/HighlightBulletsBackground.cs
  PowerPointLabs/PowerPointLabs/HighlightLab/HighlightBulletsText.cs
  PowerPointLabs/PowerPointLabs/HighlightLab/HighlightTextFragments.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/NotesToAudio.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/RecorderTaskPane.cs
  PowerPointLabs/PowerPointLabs/Ribbon1.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1583 #1403 Suggested new feature: Paste To Fit Slide
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteLabActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFitSlide/PasteToFitSlideActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFitSlide/PasteToFitSlideEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFitSlide/PasteToFitSlideImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFitSlide/PasteToFitSlideLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFitSlide/PasteToFitSlideSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/ContextMenuContentHandler.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs
  PowerPointLabs/PowerPointLabs/PasteLab/PasteToFitSlide.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.Designer.cs
  PowerPointLabs/PowerPointLabs/Properties/Resources.resx
  PowerPointLabs/PowerPointLabs/Resources/PasteToFitSlide.png
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/TextCollection/PasteLabText.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/Test/FunctionalTest/PasteLabTest.cs
  PowerPointLabs/TestInterface/IPowerPointLabsFeatures.cs
  doc/test/PasteLab/PasteLab.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1565 #1554 SyncLab: support placeholder objects
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatUtil.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncLabShapeStorage.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/Utils/ShapeUtil.cs
  PowerPointLabs/Test/FunctionalTest/SyncLabTest.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/PlaceHolderCopyTest.cs
  PowerPointLabs/Test/UnitTest/SyncLab/BaseSyncLabTest.cs
  doc/test/CopyPlaceHolder.pptx
  doc/test/SyncLab/SyncLab.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1607 1595-SyncLab-The-Fill-Color-of-textboxes-are-inconsistent-when-using-SyncLab
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/FillFormat.cs
  PowerPointLabs/Test/FunctionalTest/SyncLabTest.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1617 #1544-Copy-Operation-Made-The-Text-Disappear
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/FontColorFormat.cs
  PowerPointLabs/PowerPointLabs/Utils/ShapeUtil.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1616 #1596 Fix error for adding captions without notes in PPT 2010
  PowerPointLabs/PowerPointLabs/CaptionsLab/NotesToCaptions.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1594 #1569 support syncing properties of pictures
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/PictureEffectsFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/PositionHeightFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/PositionWidthFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/Utils/ShapeUtil.cs
  PowerPointLabs/Test/FunctionalTest/SyncLabTest.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabVisualEffectsTest.cs
  doc/test/SyncLab/SyncLab_VisualEffects.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1621 #1622: Correctly-Log-Failure-To-Sync-Font-Format
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/FontFormat.cs
Labels: s.ToReview
