Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2019-04, with the labels that each got.

#1830 #1828 MessageBox not called on UI thread
  PowerPointLabs/PowerPointLabs/ColorsLab/ColorsLabPaneWPF.xaml.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1831 #1827 Add to common traps doc: Grouping shapes with ShapeRange
  doc/CommonTraps.md
Labels: s.ToReview

#1811 #478 Add recent colors to ColorsLab
  PowerPointLabs/PowerPointLabs/ColorsLab/ColorsLabPaneWPF.xaml
  PowerPointLabs/PowerPointLabs/ColorsLab/ColorsLabPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/ColorsLab/HSLColor.cs
  PowerPointLabs/PowerPointLabs/DataSources/ColorDataSource.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/ColorsLabController.cs
  PowerPointLabs/Test/FunctionalTest/ColorsLabTest.cs
  PowerPointLabs/TestInterface/IColorsLabController.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1851 #1850 Enhance eLL loading process
  PowerPointLabs/PowerPointLabs/ELearningLab/Service/StorageService/ELearningLabTextStorageService.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ELearningLabMainPanel.xaml.cs
  PowerPointLabs/PowerPointLabs/TextCollection/ELearningLabText.cs
Labels: ok-2013, ok-2016, s.ToReview

#1840 #1838 Narrations Lab: Some animations not removed
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: s.ToReview

#1826 #1825 Add Progress Bar mode to TimerLab
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/TimerLabController.cs
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLabConstants.cs
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLabPaneWPF.xaml
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLabPaneWPF.xaml.cs
  PowerPointLabs/Test/FunctionalTest/TimerLabTest.cs
  PowerPointLabs/TestInterface/ITimerLabController.cs
  doc/test/TimerLab/TimerLab.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1839 #1833 Shortcuts Lab: Export slide as image
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/ContextMenuContentHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/ExportSlideAsImage/ExportSlideAsImageActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/ExportSlideAsImage/ExportSlideAsImageImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/ExportSlideAsImage/ExportSlideAsImageLabelHandler.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.Designer.cs
  PowerPointLabs/PowerPointLabs/Properties/Resources.resx
  PowerPointLabs/PowerPointLabs/Resources/ExportSlideAsPicture.png
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/ShortcutsLab/ShortcutsLabConstants.cs
  PowerPointLabs/PowerPointLabs/TextCollection/ShortcutsLabText.cs
  PowerPointLabs/PowerPointLabs/Utils/GraphicsUtil.cs
Labels: ok-2010, ok-2016, s.ToReview

#1843 #1836 TooltipsLab: Unit Tests
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/TooltipsLab/CreateCalloutTest.cs
  PowerPointLabs/Test/UnitTest/TooltipsLab/CreateTooltipTest.cs
  PowerPointLabs/Test/UnitTest/TooltipsLab/CreateTriggerTest.cs
  doc/test/TooltipsLab/CreateCallout.pptx
  doc/test/TooltipsLab/CreateTooltip.pptx
  doc/test/TooltipsLab/CreateTrigger.pptx
Labels: s.ToReview

#1804 (Tooltips lab) Add settings
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Settings/TooltipsLabSettingImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Settings/TooltipsLabSettingsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Settings/TooltipsLabSettingsLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Settings/TooltipsLabSettingsSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsActionHandler.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.Designer.cs
  PowerPointLabs/PowerPointLabs/Properties/Resources.resx
  PowerPointLabs/PowerPointLabs/Resources/Animation Appear.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Bounce.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Fade.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Float In.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Fly In.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Grow & Turn.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Random Bars.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Shape.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Split.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Swivel.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Wheel.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Wipe.png
  PowerPointLabs/PowerPointLabs/Resources/Animation Zoom.png
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/TooltipsLab/ConvertToTooltip.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/CreateTooltip.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/TooltipsLabConstants.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/TooltipsLabSettings.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsAnimationEntry.xaml
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsAnimationEntry.xaml.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsDialogBox.xaml
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsDialogBox.xaml.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsShapeEntry.xaml
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsShapeEntry.xaml.cs
Labels: ok-2010, ok-2016, s.ToReview

#1791 #1264 Port Shapes Lab to WPF
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/AddShape/AddShapeActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/ShapesLabActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/ShapesLabMenu/ShapesLabMenuImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/ShapesLabMenu/ShapesLabMenuLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/ShapesLabMenu/ShapesLabMenuSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/AddCustomShape/AddCustomShapeActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/AddCustomShape/AddCustomShapeImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/AddCustomShape/AddCustomShapeShapeLabelHandler.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/ShapesLabController.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.Designer.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.resx
  PowerPointLabs/PowerPointLabs/ShapesLab/LabeledThumbnail.Designer.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/LabeledThumbnail.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/LabeledThumbnail.resx
  PowerPointLabs/PowerPointLabs/ShapesLab/ShapesLabUtils.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomComboBoxItem.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomMenuItem.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomShapePaneItem.xaml
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomShapePaneItem.xaml.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomShapePaneWPF.xaml
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomShapePaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/ShapesLabCategoryInfoDialogBox.xaml.cs
  PowerPointLabs/PowerPointLabs/TextCollection/ShapesLabText.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/PowerPointLabs/Views/CustomPaintTextBox.cs
  PowerPointLabs/Test/FunctionalTest/ShapesLabTest.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/TestInterface/IShapesLabController.cs
  PowerPointLabs/TestInterface/IShapesLabLabeledThumbnail.cs
  PowerPointLabs/TestInterface/TestInterface.csproj
Labels: ok-2010, ok-2016, s.ToReview

#1864 #1863 Strikethrough voice label if the voice does not exist on local machine
  PowerPointLabs/PowerPointLabs/ELearningLab/ELearningWorkspace/Model/ClickItem/ExplanationItem.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Service/ELearningService.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Service/FunctionService/AudioService.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ELearningLabMainPanel.xaml.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ExplanationItemView.xaml
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ExplanationItemView.xaml.cs
  PowerPointLabs/PowerPointLabs/TextCollection/ELearningLabText.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1849 e-Learning Lab UI updates
  PowerPointLabs/PowerPointLabs/ActionFramework/ELearningLab/ELearningLabMenu/ELearningLabMenuImageHandler.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/AudioPreviewViews/AudioPreviewPage.xaml
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/AudioPreviewViews/AudioPreviewPage.xaml.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ExplanationItemView.xaml
  PowerPointLabs/PowerPointLabs/TextCollection/ELearningLabText.cs
Labels: s.ToReview

#1845 #1844 Reserved names Windows files can be used in ShapesLab categories
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/ShapesLabCategoryInfoDialogBox.xaml.cs
  PowerPointLabs/PowerPointLabs/TextCollection/CommonText.cs
Labels: ok-2016

#1853 #1846 eLL: eLL disappears when no slide is selected
  PowerPointLabs/PowerPointLabs/ActionFramework/ELearningLab/ELearningTaskPane/ELearningEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ELearningLabMainPanel.xaml
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ELearningLabMainPanel.xaml.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/TextCollection/ELearningLabText.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1862 #1836 Add Unit Tests for TooltipsLab
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/ConvertToTooltip/ConvertToTooltipActionHandler.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/ConvertToTooltip.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/TooltipsLab/ConvertToTooltipTest.cs
  doc/test/TooltipsLab/ConvertToTooltip.pptx
Labels: ok-2016
