Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2019-03, with the labels that each got.

#1789 #1374 Disable rotation mode when exception is caught
  PowerPointLabs/PowerPointLabs/PositionsLab/PositionsPaneWPF.xaml.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1795 New Lab: Tooltips lab
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/AssignTooltip/AssignTooltipActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/AssignTooltip/AssignTooltipEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/AssignTooltip/AssignTooltipImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/AssignTooltip/AssignTooltipLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/AssignTooltip/AssignTooltipSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateCallout/CreateCalloutActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateCallout/CreateCalloutImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateCallout/CreateCalloutLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateCallout/CreateCalloutSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateMenu/CreateMenuEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateMenu/CreateMenuImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateMenu/CreateMenuLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTooltip/CreateTooltipActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTooltip/CreateTooltipImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTooltip/CreateTooltipLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTooltip/CreateTooltipSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTrigger/CreateTriggerActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTrigger/CreateTriggerImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTrigger/CreateTriggerLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTrigger/CreateTriggerSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabMenu/TooltipsLabMenuImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabMenu/TooltipsLabMenuLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabMenu/TooltipsLabMenuSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/TextCollection/TooltipsLabText.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/AddTextbox.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/AssignToolTip.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/CreateTooltip.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/TooltipsLabConstants.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1798 #1756 Prevent illegal adjustment of GridSplitter
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/PictureSlidesLabWindow.xaml
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/PictureSlidesLabWindow.xaml.cs
Labels: ok-2010, ok-2013, ok-2016

#1816 #1765 Use of != null in This Addin
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: ok-2016, s.ToReview

#1805 #1769 Replace .Copy() and .Paste() in ZoomToArea with .Duplicate()
  PowerPointLabs/PowerPointLabs/CropLab/CropToShape.cs
  PowerPointLabs/PowerPointLabs/Models/PowerPointDeMagnifyingSlide.cs
  PowerPointLabs/PowerPointLabs/Models/PowerPointMagnifyingSlide.cs
  PowerPointLabs/PowerPointLabs/ZoomLab/ZoomToArea.cs
Labels: ok-2010, ok-2013

#1819 #1814 Remove textbox from callout in TooltipsLab
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateCallout/CreateCalloutActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTooltip/CreateTooltipActionHandler.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/TooltipsLab/AddTextbox.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/CreateTooltip.cs
Labels: ok-2013, ok-2016, s.ToReview

#1820 #1813 New Icons and Menu Structure
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/AssignTooltip/AssignTooltipImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/ConvertToTooltip/ConvertToTooltipActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/ConvertToTooltip/ConvertToTooltipEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/ConvertToTooltip/ConvertToTooltipImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/ConvertToTooltip/ConvertToTooltipLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/ConvertToTooltip/ConvertToTooltipSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateMenu/CreateMenuLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/Create/CreateTooltip/CreateTooltipImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateCallout/CreateCalloutActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateCallout/CreateCalloutEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateCallout/CreateCalloutImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateCallout/CreateCalloutLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateCallout/CreateCalloutSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTooltip/CreateTooltipActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTooltip/CreateTooltipImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTooltip/CreateTooltipLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTooltip/CreateTooltipSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTrigger/CreateTriggerActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTrigger/CreateTriggerEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTrigger/CreateTriggerImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTrigger/CreateTriggerLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/CreateTrigger/CreateTriggerSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabMenu/TooltipsLabMenuImageHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsLabelHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/TooltipsLab/TooltipsLabSettings/TooltipsLabSettingsSupertipHandler.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.Designer.cs
  PowerPointLabs/PowerPointLabs/Properties/Resources.resx
  PowerPointLabs/PowerPointLabs/Resources/ConvertToTooltip.png
  PowerPointLabs/PowerPointLabs/Resources/CreateCallout.png
  PowerPointLabs/PowerPointLabs/Resources/CreateTooltip.png
  PowerPointLabs/PowerPointLabs/Resources/CreateTrigger.png
  PowerPointLabs/PowerPointLabs/Resources/TooltipsLab.png
  PowerPointLabs/PowerPointLabs/Ribbon1.xml
  PowerPointLabs/PowerPointLabs/TextCollection/TooltipsLabText.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/ConvertToTooltip.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1822 #1815 Tooltips Lab: Change default callout and trigger shape styles
  PowerPointLabs/PowerPointLabs/ELearningLab/Utility/ShapeUtility.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/CreateTooltip.cs
  PowerPointLabs/PowerPointLabs/Utils/ShapeUtil.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview
