Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2019-06, with the labels that each got.

#1920 #1911 Explanation items does not load correctly
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ELearningLabMainPanel.xaml.cs
Labels: ok-2010, ok-2016

#1914 #1745 Limit the maximum number of open labs panes
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointOperations.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/Test/FunctionalTest/AutoNarrationTest.cs
  PowerPointLabs/Test/FunctionalTest/BaseFunctionalTest.cs
  PowerPointLabs/Test/FunctionalTest/EffectsLabTest.cs
  PowerPointLabs/Test/FunctionalTest/LimitOpenPanesTest.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/Util/UnitTestPpOperations.cs
  PowerPointLabs/TestInterface/IPowerPointOperations.cs
Labels: ok-2010, ok-2016

#1923 #1922 E-learning settings voice ranking disappears
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/AudioSettingsViews/AudioMainSettingsPage.xaml.cs
Labels: ok-2016

#1933 #1900 ColorsLab Eyedropper bug
  PowerPointLabs/PowerPointLabs/ColorsLab/ColorsLabPaneWPF.xaml.cs
Labels: ok-2010, ok-2016

#1932 #1931 Highly duplicated code for converting between media color and drawing color
  PowerPointLabs/PowerPointLabs/ColorsLab/ColorInformationDialog.xaml.cs
  PowerPointLabs/PowerPointLabs/ColorsLab/ColorsLabPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ELearningWorkspaceConverters/AnimationTypeToImageSourceConverter.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ELearningLabMainPanel.xaml.cs
  PowerPointLabs/PowerPointLabs/ELearningLab/Views/ELearningWorkspaceViews/ExplanationItemView.xaml.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Util/ImageUtil.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/AdjustImageWindow.xaml.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/PictureSlidesLabWindow.xaml.VariationStageControls.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/PictureSlidesLabWindow.xaml.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/QuickDropDialog.xaml.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/Views/SettingsFlyout.xaml.cs
  PowerPointLabs/PowerPointLabs/SaveLab/Views/SaveLabSettingsDialogBox.xaml.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomShapePaneItem.xaml.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/CustomShapePaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/Views/ShapesLabSettingsDialogBox.xaml.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatListItem.xaml.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatPaneItem.xaml.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsAnimationEntry.xaml.cs
  PowerPointLabs/PowerPointLabs/TooltipsLab/Views/TooltipsLabSettingsShapeEntry.xaml.cs
  PowerPointLabs/PowerPointLabs/Utils/CommonUtil.cs
  PowerPointLabs/PowerPointLabs/Utils/GraphicsUtil.cs
Labels: s.ToReview
