Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2019-01, with the labels that each got.

#1738 #1735 Visual Studio modifies files in .vs folder not in .gitignore
  .gitignore
Labels: s.ToReview

#1739 #1736 Update Contributing Doc
  .github/CONTRIBUTING.md
Labels: a-Documents, s.ToReview

#1730 #1718 TimerLab: give option for countdown timer
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/TimerLabController.cs
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLabConstants.cs
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLabPaneWPF.xaml
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLabPaneWPF.xaml.cs
  PowerPointLabs/Test/FunctionalTest/TimerLabTest.cs
  PowerPointLabs/TestInterface/ITimerLabController.cs
  doc/test/TimerLab/TimerLab.pptx
Labels: ok-2016

#1715 #1647 TimerLab error when no slides selected or empty ppt
  PowerPointLabs/PowerPointLabs/ActionFramework/TimerLab/TimerLabEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/PowerPointLabs/TimerLab/TimerLab.cs
Labels: ok-2013, ok-2016
