Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2019-02, with the labels that each got.

#1764 #1737 Convert to Picture: Unsupported Object
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.cs
  PowerPointLabs/PowerPointLabs/ShortcutsLab/ConvertToPicture.cs
  PowerPointLabs/Test/FunctionalTest/ShapesLabTest.cs
  PowerPointLabs/Test/Util/MessageBoxUtil.cs
  doc/test/ShapesLab/ShapesLab.pptx
Labels: ok-2013, ok-2016, s.ToReview

#1725 Integrate Azure speech services to narrations lab
  PowerPointLabs/.vs/config/applicationhost.config
  PowerPointLabs/PowerPointLabs/ActionFramework/NarrationsLab/AddNarrations/AddNarrationsActionHandler.cs
  PowerPointLabs/PowerPointLabs/ActionFramework/NarrationsLab/NarrationsLabSettings/NarrationsLabSettingsActionHandler.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/AudioOutputFormat.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/AzureVoice.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/AzureVoiceList.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/EndpointToUriMapping.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/Gender.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/Locale.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/LocaleMapping.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/NarrationsLabSettingsPage.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/UserAccount.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Data/Voice.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/NarrationsLabSettings.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/NotesToAudio.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Storage/NarrationsLabStorageConfig.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/ValueConverters/BaseValueConverter.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/ValueConverters/NarrationsLabSettingsPageValueConverter.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/ViewModel/Authentication.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/ViewModel/GenericEventArgs.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/ViewModel/Synthesize.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/AzureVoiceLoginPage.xaml
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/AzureVoiceLoginPage.xaml.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/NarrationsLabMainSettingsPage.xaml
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/NarrationsLabMainSettingsPage.xaml.cs
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/NarrationsLabSettingsDialogBox.xaml
  PowerPointLabs/PowerPointLabs/NarrationsLab/Views/NarrationsLabSettingsDialogBox.xaml.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.Designer.cs
  PowerPointLabs/PowerPointLabs/Properties/Settings.Designer.cs
  PowerPointLabs/PowerPointLabs/SpeechEngine/TextToSpeech.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.Designer.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.Designer.xml
  PowerPointLabs/PowerPointLabs/Views/ProcessingStatusForm.Designer.cs
  PowerPointLabs/PowerPointLabs/app.config
  PowerPointLabs/Test/Test.csproj
Labels: ok-2010, ok-2013, ok-2016

#1761 #195 Increase resolution of images in ZoomLab
  PowerPointLabs/PowerPointLabs/Utils/FileDir.cs
  PowerPointLabs/PowerPointLabs/ZoomLab/AutoZoom.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1760 #1604 Disable SyncLab/ShapesLab button when there is no selection
  PowerPointLabs/PowerPointLabs/ActionFramework/ShapesLab/ShapesLabActionHandler.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/ShapesLabController.cs
  PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/Controller/SyncLabController.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/Properties/Resources.Designer.cs
  PowerPointLabs/PowerPointLabs/Properties/Resources.resx
  PowerPointLabs/PowerPointLabs/Resources/AddToCustomShapesDisabled.png
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.Designer.cs
  PowerPointLabs/PowerPointLabs/ShapesLab/CustomShapePane.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPane.Designer.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/TextCollection/ShapesLabText.cs
  PowerPointLabs/PowerPointLabs/TextCollection/SyncLabText.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
  PowerPointLabs/Test/FunctionalTest/ShapesLabTest.cs
  PowerPointLabs/Test/FunctionalTest/SyncLabTest.cs
  PowerPointLabs/TestInterface/IShapesLabController.cs
  PowerPointLabs/TestInterface/ISyncLabController.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1746 #1432 Close background ppts on closing of main window
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncPaneWPF.xaml.cs
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1776 #1755 Disable PictureSlidesLab on empty presentation
  PowerPointLabs/PowerPointLabs/ActionFramework/PictureSlidesLab/PictureSlidesEnabledHandler.cs
  PowerPointLabs/PowerPointLabs/PictureSlidesLab/PictureSlidesLab.cs
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/ThisAddIn.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1781 #26 Open SelectionPane after editting name
  PowerPointLabs/PowerPointLabs/ActionFramework/ShortcutsLab/EditName/EditNameActionHandler.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1747 #1272 Shows details of copied formats in tooltips
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatPaneItem.xaml
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatPaneItem.xaml.cs
  PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatPanelItemStub.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabFormatPaneItemTest.cs
Labels: ok-2010, ok-2013, ok-2016, s.ToReview

#1766 #1209 improve text sync
  PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/TextHorizontalAlignmentFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/TextLineSpacingFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/TextOrientationFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/ObjectFormats/TextVerticalAlignmentFormat.cs
  PowerPointLabs/PowerPointLabs/SyncLab/SyncFormatConstants.cs
  PowerPointLabs/Test/Test.csproj
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabTextAlignmentTest.cs
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabTextLineSpacing.cs
  PowerPointLabs/Test/UnitTest/SyncLab/SyncLabTextOrientation.cs
  doc/test/SyncLab/SyncLab_Text.pptx
Labels: ok-2010, ok-2013, ok-2016, s.ToReview
