Repository PowerPointLabs/PowerPointLabs, pull requests merged in 2020-03, with the labels that each got.

#2006 #1947 HighlightLab bug: Background & Point highlight overwrite each other
  PowerPointLabs/PowerPointLabs/HighlightLab/HighlightBulletsBackground.cs
  PowerPointLabs/PowerPointLabs/HighlightLab/HighlightBulletsText.cs
Labels: ok-2010, ok-2013, ok-2016

#2001 #2000 Convert ShapesToTooltip UT failing
  PowerPointLabs/Test/Util/WindowWatcher.cs
Labels: ok-2010, ok-2013, ok-2016

#2011 Add preview for background highlight points
  PowerPointLabs/PowerPointLabs/HighlightLab/HighlightBulletsBackground.cs
Labels: ok-2010, ok-2016

#2015 #1370 paste into group exception after undo
  PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteIntoGroup/PasteIntoGroupActionHandler.cs
Labels: ok-2013, ok-2016
